checks:
    php: true

filter:
    paths:
        - 'avatar-privacy.php'
        - 'admin/'
        - 'public/'
        - 'includes/'
    dependency_paths:
        - wordpress/

build:
    cache:
        directories:
            - ~/.composer   # Composer home directory (avoid fetching already fetched packages)
            # vendor is already included.
    environment:
        rabbitmq: false
        mysql: false
        postgresql: false
        mongodb: false
        elasticsearch: false
        redis: false
        memcached: false
        neo4j: false
        php:
            version: 7.4
            compile_options: '--with-config-file-path=/home/scrutinizer/.phpenv/versions/7.4.3/etc --with-config-file-scan-dir=/home/scrutinizer/.phpenv/versions/7.4.3/etc/conf.d --prefix=/home/scrutinizer/.phpenv/versions/7.4.3 --libexecdir=/home/scrutinizer/.phpenv/versions/7.4.0/libexec --enable-intl --with-openssl --without-pear --with-gd --enable-gd --with-jpeg-dir=/usr --with-png-dir=/usr --with-freetype-dir=/usr --enable-exif --with-libzip --with-zlib --with-zlib-dir=/usr --with-sodium --with-pdo-sqlite --enable-soap --enable-xmlreader --with-xsl --enable-ftp --with-tidy --with-xmlrpc --enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-shmop --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --enable-pcntl --with-readline --enable-mbstring --with-curl --with-pgsql --with-pdo-pgsql --with-gettext --enable-sockets --with-bz2 --enable-bcmath --enable-calendar --with-libdir=lib --enable-fpm --enable-maintainer-zts --with-gmp --with-kerberos --with-imap --with-imap-ssl --with-apxs2=/usr/bin/apxs --with-ldap --with-pear=/home/scrutinizer/.phpenv/versions/7.4.3/pear'

    nodes:
        analysis:
            project_setup:
                override: true
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress-core
                    - composer require --dev wp-cli/wp-cli
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
                    - phpcs-run --standard=phpcs.xml avatar-privacy.php admin/ public/ includes/ --extensions=php

tools:
    php_code_sniffer: false
    php_cs_fixer: false
    external_code_coverage: true
